import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { mergeLangpackEntries } from '../../web/export/langpackMerge';
import { parseVortexDeployment } from '../deploymentManifest';
import {
  discoverVortexExportOrder,
  filterVortexLangpackMods,
  orderVortexLangpackModIds,
} from '../exportOrder';
import { parsePluginList } from '../pluginsTxt';

describe('parsePluginList', () => {
  it('reads load order and starred enabled plugins', () => {
    const parsed = parsePluginList(`# Automatically generated by Vortex
Fallout4.esm
DLCRobot.esm
*unofficial fallout 4 patch.esp
M8rDisablePipboyEffects.esp
`);
    expect(parsed.plugins).toEqual([
      'Fallout4.esm',
      'DLCRobot.esm',
      'unofficial fallout 4 patch.esp',
      'M8rDisablePipboyEffects.esp',
    ]);
    expect(parsed.enabled).toEqual(['unofficial fallout 4 patch.esp']);
  });
});

describe('parseVortexDeployment', () => {
  it('keeps the first winner per path', () => {
    const files = parseVortexDeployment({
      files: [
        { relPath: 'Interface\\PipboyMenu.swf', source: 'FallUI VR-Patch' },
        { relPath: 'Data/Interface/PipboyMenu.swf', source: 'FallUI Inventory' },
        { relPath: 'Interface/Translate_en.txt', source: 'FallUI VR-Patch' },
      ],
    });
    expect(files).toEqual([
      { relPath: 'Interface/PipboyMenu.swf', sourceFolder: 'FallUI VR-Patch' },
      { relPath: 'Interface/Translate_en.txt', sourceFolder: 'FallUI VR-Patch' },
    ]);
  });
});

describe('filterVortexLangpackMods', () => {
  const rows = [
    {
      id: 1,
      name: 'Fallout4',
      channel: 'game',
      abs_path: 'C:/game/Data/Fallout4.esm',
      source_folder: null,
    },
    {
      id: 2,
      name: 'UFO4P',
      channel: 'mods',
      abs_path: 'C:/mods/unofficial fallout 4 patch.esp',
      source_folder: 'Unofficial Fallout 4 Patch',
    },
    {
      id: 3,
      name: 'Disabled Patch',
      channel: 'mods',
      abs_path: 'C:/mods/Disabled.esp',
      source_folder: 'Disabled Patch-1-1',
      pluginFileName: 'Disabled.esp',
    },
    {
      id: 4,
      name: 'FallUI HUD',
      channel: 'mods',
      abs_path: null,
      source_folder: 'FallUI - HUD-51813',
    },
  ];

  it('keeps game and deployed staging folders, ignoring plugins.txt stars', () => {
    const kept = filterVortexLangpackMods(rows, {
      plugins: ['Fallout4.esm', 'unofficial fallout 4 patch.esp', 'Disabled.esp'],
      enabledPlugins: ['unofficial fallout 4 patch.esp'],
      fileWinners: [
        { path: 'unofficial fallout 4 patch.esp', sourceFolder: 'Unofficial Fallout 4 Patch' },
        { path: 'Interface/HUDMenu.swf', sourceFolder: 'FallUI - HUD-51813' },
        { path: 'Disabled.esp', sourceFolder: 'Disabled Patch-1-1' },
      ],
    });
    expect(kept.map((row) => row.id)).toEqual([1, 2, 3, 4]);
  });

  it('drops a staging mod whose folder is not in the deployment', () => {
    const kept = filterVortexLangpackMods(rows, {
      plugins: ['Fallout4.esm', 'Disabled.esp'],
      enabledPlugins: ['Disabled.esp'],
      fileWinners: [
        { path: 'unofficial fallout 4 patch.esp', sourceFolder: 'Unofficial Fallout 4 Patch' },
      ],
    });
    expect(kept.map((row) => row.id)).toEqual([1, 2]);
  });
});

describe('orderVortexLangpackModIds', () => {
  it('orders plugins by load order, then folders by deployment', () => {
    const ids = orderVortexLangpackModIds(
      [
        {
          id: 3,
          name: 'FallUI Inventory',
          channel: 'mods',
          abs_path: null,
          source_folder: 'FallUI - Inventory-48758',
          pluginFileName: 'M8rDisablePipboyEffects.esp',
        },
        {
          id: 1,
          name: 'Fallout4',
          channel: 'game',
          abs_path: 'C:/game/Data/Fallout4.esm',
          source_folder: null,
        },
        {
          id: 2,
          name: 'UFO4P',
          channel: 'mods',
          abs_path: 'C:/mods/unofficial fallout 4 patch.esp',
          source_folder: 'Unofficial Fallout 4 Patch',
        },
        {
          id: 4,
          name: 'FallUI HUD',
          channel: 'mods',
          abs_path: null,
          source_folder: 'FallUI - HUD-51813',
        },
      ],
      {
        plugins: ['Fallout4.esm', 'unofficial fallout 4 patch.esp', 'M8rDisablePipboyEffects.esp'],
        fileWinners: [
          { path: 'Interface/HUDMenu.swf', sourceFolder: 'FallUI - HUD-51813' },
          { path: 'Interface/BarterMenu.swf', sourceFolder: 'FallUI - Inventory-48758' },
        ],
      },
    );
    expect(ids).toEqual([1, 2, 3, 4]);
  });
});

describe('mergeLangpackEntries file winners', () => {
  it('keeps the Vortex winner even when a later mod wrote the same path', () => {
    const merged = mergeLangpackEntries(
      [
        {
          entry: { name: 'Interface/PipboyMenu.swf', data: Buffer.from('inventory') },
          sourceFolder: 'FallUI - Inventory-48758-2-2-1-1666954336',
        },
        {
          entry: { name: 'Interface/PipboyMenu.swf', data: Buffer.from('vr') },
          sourceFolder: '(Experimental) FallUI VR-Patch-48758-1-12-1-vr-exp3-1618625274',
        },
      ],
      [
        {
          path: 'Interface/PipboyMenu.swf',
          sourceFolder: '(Experimental) FallUI VR-Patch-48758-1-12-1-vr-exp3-1618625274',
        },
      ],
    );
    expect(merged).toHaveLength(1);
    expect(merged[0]?.data?.toString()).toBe('vr');
  });

  it('keeps en and ru winners on their own paths', () => {
    const merged = mergeLangpackEntries(
      [
        {
          entry: {
            name: 'Interface/FallUI HUD/Translation/Translate_en.txt',
            data: Buffer.from('hud-en'),
          },
          sourceFolder: 'FallUI - HUD-51813',
        },
        {
          entry: {
            name: 'Interface/FallUI HUD/Translation/Translate_ru.txt',
            data: Buffer.from('hud-ru-from-en'),
          },
          sourceFolder: 'FallUI - HUD-51813',
        },
        {
          entry: {
            name: 'Interface/FallUI HUD/Translation/Translate_ru.txt',
            data: Buffer.from('hud-ru-pack'),
          },
          sourceFolder: 'FallUI HUD - RU-51827',
        },
      ],
      [
        {
          path: 'Interface/FallUI HUD/Translation/Translate_en.txt',
          sourceFolder: 'FallUI - HUD-51813',
        },
        {
          path: 'Interface/FallUI HUD/Translation/Translate_ru.txt',
          sourceFolder: 'FallUI HUD - RU-51827',
        },
      ],
    );
    const byName = Object.fromEntries(merged.map((file) => [file.name, file.data?.toString()]));
    expect(byName['Interface/FallUI HUD/Translation/Translate_en.txt']).toBe('hud-en');
    expect(byName['Interface/FallUI HUD/Translation/Translate_ru.txt']).toBe('hud-ru-pack');
  });
});

describe('discoverVortexExportOrder', () => {
  it('reads loadorder.txt and vortex.deployment.json next to staging', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'vortex-order-'));
    try {
      const staging = path.join(root, 'mods');
      fs.mkdirSync(staging, { recursive: true });
      fs.writeFileSync(
        path.join(root, 'loadorder.txt'),
        '# test\nFallout4.esm\nunofficial fallout 4 patch.esp\n',
      );
      fs.writeFileSync(
        path.join(staging, 'vortex.deployment.json'),
        JSON.stringify({
          deploymentMethod: 'hardlink_activator',
          files: [
            {
              relPath: 'Interface\\Translate_en.txt',
              source: '(Experimental) FallUI VR-Patch-48758-1-12-1-vr-exp3-1618625274',
            },
          ],
        }),
      );
      const found = discoverVortexExportOrder({
        game: 'fo4',
        stagingPath: staging,
        pluginsTxt: path.join(root, 'loadorder.txt'),
      });
      expect(found.plugins[0]).toBe('Fallout4.esm');
      expect(found.plugins).toContain('unofficial fallout 4 patch.esp');
      expect(found.fileWinners).toEqual([
        {
          path: 'Interface/Translate_en.txt',
          sourceFolder: '(Experimental) FallUI VR-Patch-48758-1-12-1-vr-exp3-1618625274',
        },
      ]);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });
});
