/**
 * Formal status state machine for translation strings.
 *
 * Every status change in the system must be validated against this module.
 * It defines all valid statuses, the actors who may perform transitions, and
 * the exact set of allowed transitions between states.
 *
 * Status lifecycle diagram:
 *
 *   (new string, no translation yet)
 *         │
 *         ▼ (system: TM auto-apply)
 *       ┌────┐
 *       │ tm │
 *       └────┘
 *
 *         │ (system: fuzzy TM match)
 *         ▼
 *     ┌───────┐
 *     │ fuzzy │
 *     └───────┘
 *
 *         │ (system: LLM batch translation)
 *         ▼
 *     ┌──────┐
 *     │ auto │
 *     └──────┘
 *
 *         │ (system: EET / CSV legacy import)
 *         ▼
 *     ┌───────┐
 *     │ human │
 *     └───────┘
 *
 *         │ (translator / admin: manual save)
 *         ▼
 *     ┌───────┐
 *     │ draft │ ◄──── rejected strings re-opened by translator
 *     └───┬───┘
 *         │
 *         │ (reviewer / admin: approve)
 *         ▼
 *   ┌──────────┐
 *   │ reviewed │
 *   └────┬─────┘
 *        │ (reviewer / admin: reject)
 *        ▼
 *   ┌──────────┐
 *   │ rejected │
 *   └────┬─────┘
 *        │ (translator re-edits → back to draft)
 *        └──────────────────────────────────────►
 */

import type { UserRole } from './authService';

// ── Types ─────────────────────────────────────────────────────────────────────

/**
 * All possible statuses a translation record can hold.
 *
 * - `draft`    — text saved by a translator, not yet reviewed by a reviewer.
 * - `tm`       — exact or anchor match applied automatically by the TM engine.
 * - `fuzzy`    — approximate (fuzzy) match applied by the TM engine; needs
 *                manual verification before it can be approved.
 * - `auto`     — generated by LLM batch translation; needs review.
 * - `human`    — imported from a legacy EET file; the original human translator
 *                had approved this string before export.
 * - `reviewed` — explicitly approved by a user with reviewer or admin role.
 * - `rejected` — rejected by a reviewer; awaiting correction by a translator.
 * - `deleted`  — soft-deleted record (internal; never returned as a target of a
 *                regular transition).
 */
export type TranslationStatus =
  | 'draft'
  | 'tm'
  | 'fuzzy'
  | 'auto'
  | 'human'
  | 'reviewed'
  | 'rejected'
  | 'deleted';

/**
 * The entity that is requesting a status change.
 *
 * - `'system'`     — automated pipeline (TM engine, LLM, import tools).
 *                    System actors bypass all transition constraints so that
 *                    automated processes can always write freely.
 * - `'translator'` — regular human user; can save drafts and re-open rejected strings.
 * - `'reviewer'`   — human reviewer; can approve and reject translations.
 * - `'admin'`      — superuser; can perform any transition.
 *
 * `UserRole` is `'admin' | 'reviewer' | 'translator'` (from authService.ts).
 */
export type StatusActor = 'system' | UserRole;

/**
 * A single rule in the transition table.
 */
type TransitionRule = {
  /**
   * The statuses the translation must currently have for this rule to apply.
   * null means "any current status (including no translation yet)".
   */
  from: TranslationStatus[] | null;

  /** The status that will be assigned if this transition is executed. */
  to: TranslationStatus;

  /** Which actors are allowed to execute this transition. */
  actors: StatusActor[];

  /** Human-readable description of the action that triggers this transition. */
  action: string;
};

// ── Transition table ──────────────────────────────────────────────────────────

/**
 * Complete, ordered list of allowed transitions.
 *
 * Rules are evaluated top-to-bottom; the first matching rule is used.
 * A rule matches when ALL three conditions hold:
 *   1. `rule.to === targetStatus`
 *   2. `actor` is listed in `rule.actors`
 *   3. `rule.from` is null, OR `currentStatus` is in `rule.from`
 */
const TRANSITIONS: TransitionRule[] = [
  // ── System-only automated writes ───────────────────────────────────────────

  {
    from: null,
    to: 'tm',
    actors: ['system'],
    action: 'TM exact / anchor match auto-apply',
  },
  {
    from: null,
    to: 'fuzzy',
    actors: ['system'],
    action: 'TM fuzzy match auto-apply',
  },
  {
    from: null,
    to: 'auto',
    actors: ['system'],
    action: 'LLM batch translation',
  },
  {
    from: null,
    to: 'human',
    actors: ['system'],
    action: 'EET / CSV legacy import',
  },

  // ── Manual text save (creates or replaces a translation as draft) ──────────
  //
  // Any actor that can edit may save a new draft.  This intentionally covers
  // all actors including 'system', because upsertTranslation always uses
  // 'draft' when called from the web editor.
  {
    from: null,
    to: 'draft',
    actors: ['system', 'translator', 'reviewer', 'admin'],
    action: 'Save translation text',
  },

  // ── Reviewer / admin: approve ──────────────────────────────────────────────
  //
  // A translation in any "pending review" state may be approved.
  // Approved (reviewed) and already-rejected strings cannot be re-approved
  // without first going through draft again, which provides an audit trail.
  {
    from: ['draft', 'tm', 'fuzzy', 'auto', 'human'],
    to: 'reviewed',
    actors: ['reviewer', 'admin'],
    action: 'Approve translation',
  },

  // ── Reviewer / admin: reject ───────────────────────────────────────────────
  //
  // Any translated string (including already-approved ones) may be rejected.
  // This allows reviewers to correct past approvals.
  {
    from: ['draft', 'tm', 'fuzzy', 'auto', 'human', 'reviewed'],
    to: 'rejected',
    actors: ['reviewer', 'admin'],
    action: 'Reject translation',
  },
];

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Checks whether the transition `from` → `to` is permitted for `actor`.
 *
 * @param from  Current status of the translation.  Pass `null` when no
 *              translation record exists yet (first-time write).
 * @param to    The status being requested.
 * @param actor The entity requesting the change.
 * @returns     `true` if the transition is allowed; `false` otherwise.
 */
export const canTransition = (
  from: TranslationStatus | null,
  to: TranslationStatus,
  actor: StatusActor,
): boolean => {
  // System actor is always unrestricted so that automated pipelines
  // (TM engine, LLM, import jobs) can write any status at any time.
  if (actor === 'system') return true;

  for (const rule of TRANSITIONS) {
    if (rule.to !== to) continue;
    if (!rule.actors.includes(actor)) continue;
    // null means "from any state" — the `from` check is skipped.
    if (rule.from !== null && from !== null && !rule.from.includes(from)) continue;
    return true;
  }
  return false;
};

/**
 * Validates `from` → `to` for `actor` and throws a descriptive error when
 * the transition is illegal.
 *
 * The thrown error carries `statusCode: 403` so route handlers can forward it
 * directly to the client without extra wrapping.
 *
 * @param from  Current status (or `null` if the translation does not exist yet).
 * @param to    Requested new status.
 * @param actor Requesting actor.
 * @throws {Error} `statusCode: 403` when the transition is not allowed.
 */
export const assertTransition = (
  from: TranslationStatus | null,
  to: TranslationStatus,
  actor: StatusActor,
): void => {
  if (!canTransition(from, to, actor)) {
    throw Object.assign(
      new Error(
        `Status transition '${from ?? 'none'}' → '${to}' is not allowed for actor '${actor}'`,
      ),
      { statusCode: 403 },
    );
  }
};

/**
 * Returns all statuses that `actor` can legally transition to from `from`.
 *
 * Useful for building permission-aware dropdowns and keyboard actions in the
 * editor UI (fetch this list and enable only those options).
 *
 * @param from  Current status of the translation.
 * @param actor Requesting actor.
 * @returns     Array of reachable statuses (may be empty).
 */
export const reachableStatuses = (
  from: TranslationStatus,
  actor: StatusActor,
): TranslationStatus[] => {
  const targets = new Set<TranslationStatus>();
  for (const rule of TRANSITIONS) {
    if (!rule.actors.includes(actor)) continue;
    if (rule.from !== null && !rule.from.includes(from)) continue;
    targets.add(rule.to);
  }
  return [...targets];
};

/**
 * Set of all valid `TranslationStatus` string literals.
 * Use this for input validation at API boundaries.
 */
export const VALID_TRANSLATION_STATUSES = new Set<TranslationStatus>([
  'draft',
  'tm',
  'fuzzy',
  'auto',
  'human',
  'reviewed',
  'rejected',
  'deleted',
]);

/**
 * Type guard: returns true if `s` is a valid `TranslationStatus`.
 *
 * @param s  Any string received from user input or the database.
 */
export const isValidTranslationStatus = (s: string): s is TranslationStatus =>
  VALID_TRANSLATION_STATUSES.has(s as TranslationStatus);
