/**
 * Canonical Disco Elysium English → Ukrainian glossary.
 *
 * Loaded by glossary seeding and translation prompts.
 */

import type { GlossaryEntry } from './types';

export type { GlossaryEntry } from './types';

export const DISCO_UK_GLOSSARY: GlossaryEntry[] = [
  { term: 'Disco Elysium', translation: 'Disco Elysium' },
  { term: 'Revachol', translation: 'Ревашоль' },
  { term: 'Martinaise', translation: 'Мартінез' },
  { term: 'Insulinde', translation: 'Інсулінд' },
  { term: 'Jamrock', translation: 'Джемрок' },
  { term: 'La Delta', translation: 'Ла-Дельта' },
  { term: 'Precinct 41', translation: '41-й відділок' },
  { term: 'Harry Du Bois', translation: 'Гаррі Дюбуа' },
  { term: 'Harrier Du Bois', translation: 'Гаррієр Дюбуа' },
  { term: 'Kim Kitsuragi', translation: 'Кім Кіцураґі' },
  { term: 'Cuno', translation: 'Куно' },
  { term: 'Cunoesse', translation: 'Кюноесс' },
  { term: 'Pissfaggot', translation: 'сцикуняка' },
  { term: 'faggoted', translation: 'підарськи' },
  { term: 'faggots', translation: 'підари' },
  { term: 'faggot', translation: 'підар' },
  { term: 'Joyce Messier', translation: 'Джойс Мессьє' },
  { term: 'Evrart Claire', translation: 'Еврар Клер' },
  { term: 'Edgar Claire', translation: 'Едґар Клер' },
  { term: 'Klaasje', translation: 'Клаасьє' },
  { term: 'Titus Hardie', translation: 'Тітус Гарді' },
  { term: 'Measurehead', translation: 'Мірюголова' },
  { term: 'Jean Vicquemare', translation: 'Жан Вікмар' },
  { term: 'Judit Minot', translation: 'Юдіт Міно' },
  { term: 'Trant Heidelstam', translation: 'Трант Гайдельстам' },
  { term: 'Garte', translation: 'Гарт' },
  { term: 'Soona Luukanen-Kilde', translation: 'Соона Лууканен-Кільде' },
  { term: 'The Deserter', translation: 'Дезертир' },
  { term: 'Dolores Dei', translation: 'Долорес Деї' },
  { term: 'The Pale', translation: 'Блідь' },
  { term: 'RCM', translation: 'РГМ' },
  { term: 'Revachol Citizens Militia', translation: 'Громадянська міліція Ревашоля' },
  { term: 'Logic', translation: 'Логіка' },
  { term: 'Encyclopedia', translation: 'Енциклопедія' },
  { term: 'Rhetoric', translation: 'Риторика' },
  { term: 'Drama', translation: 'Драма' },
  { term: 'Conceptualization', translation: 'Концептуалізація' },
  { term: 'Visual Calculus', translation: 'Візуальне числення' },
  { term: 'Volition', translation: 'Воля' },
  { term: 'Inland Empire', translation: 'Внутрішня імперія' },
  { term: 'Empathy', translation: 'Емпатія' },
  { term: 'Authority', translation: 'Авторитет' },
  { term: 'Esprit de Corps', translation: 'Корпоративний дух' },
  { term: 'Espirit de Corps', translation: 'Корпоративний дух' },
  { term: 'Suggestion', translation: 'Навіювання' },
  { term: 'Endurance', translation: 'Витривалість' },
  { term: 'Pain Threshold', translation: 'Поріг болю' },
  { term: 'Physical Instrument', translation: 'Фізичний інструмент' },
  { term: 'Electrochemistry', translation: 'Електрохімія' },
  { term: 'Shivers', translation: 'Дрижаки' },
  { term: 'Half Light', translation: 'Напівсвітло' },
  { term: 'Hand/Eye Coordination', translation: 'Координація рук і очей' },
  { term: 'Perception', translation: 'Сприйняття' },
  { term: 'Reaction Speed', translation: 'Швидкість реакції' },
  { term: 'Savoir Faire', translation: 'Савуар-фер' },
  { term: 'Interfacing', translation: 'Інтерфейсинг' },
  { term: 'Composure', translation: 'Самовладання' },
  { term: 'Thought Cabinet', translation: 'Кабінет думок' },
  { term: 'Ancient Reptilian Brain', translation: 'Давній рептильний мозок' },
  { term: 'Limbic System', translation: 'Лімбічна система' },
  { term: 'Moralintern', translation: 'Моралінтерн' },
  { term: 'Moralism', translation: 'моралізм' },
  { term: 'Mazovianism', translation: 'мазовіанство' },
  { term: 'Ultraliberalism', translation: 'ультралібералізм' },
  { term: 'Revacholian Nationhood', translation: 'Ревашольська нація' },
  { term: 'Coalition', translation: 'Коаліція' },
  { term: 'Union', translation: 'Профспілка' },
  { term: 'Dockworkers', translation: 'докери' },
  { term: 'Hardie Boys', translation: 'Хлопці Гарді' },
  { term: 'Krenel', translation: 'Кренель' },
  { term: 'Wild Pines', translation: 'Вайлд Пайнс' },
  { term: 'Innocence', translation: 'Іноценція' },
  { term: 'Antecentennial Revolution', translation: 'Достолітня революція' },
  { term: 'Whirling-in-Rags', translation: 'Вир у лахмітті' },
  { term: 'The Hanged Man', translation: 'Повішений' },
  { term: 'Doomed Commercial Area', translation: 'Приречена комерційна зона' },
  { term: 'Capeside Apartments', translation: 'Кейпсайдські апартаменти' },
  { term: 'Insulindian Phasmid', translation: 'Інсуліндська паличниця' },
  { term: 'Coupris Kineema', translation: 'Купріс Кінема' },
  { term: 'motor carriage', translation: 'моторна карета' },
  { term: 'reál', translation: 'реал' },
  { term: 'centime', translation: 'сантим' },
  { term: 'White check', translation: 'біла перевірка' },
  { term: 'Red check', translation: 'червона перевірка' },
  { term: 'Passive check', translation: 'пасивна перевірка' },
  { term: 'Apocalypse Cop', translation: 'коп апокаліпсису' },
  { term: 'Superstar Cop', translation: 'коп-суперзірка' },
  { term: 'Hobocop', translation: 'бомжкокоп' },
  { term: 'The Expression', translation: 'Вираз' },
  { term: 'anodic music', translation: 'анодна музика' },
];
