/**
 * Fallout 4 RACE face editor glossary (FMRN / MPPN / TTGP).
 *
 * Canonical EN→UK pairs for character creation morph sliders, presets, and
 * face-detail labels. Generated from DB (mods 2/43/44) with manual overrides.
 *
 * Regenerate: `node --import tsx scripts/_analyzeRaceGlossary.ts`
 * Merged into `FO4_UK_GLOSSARY` — run `npm run db:seed:glossary` after edits.
 */
import type { GlossaryEntry } from './types';

export const FO4_RACE_UK_GLOSSARY: GlossaryEntry[] = [
  { term: 'Alert 1', translation: 'Тривога 1' },
  { term: 'Alert 2', translation: 'Тривога 2' },
  { term: 'Alert 3', translation: 'Тривога 3' },
  { term: 'Alert 4', translation: 'Тривога 4' },
  { term: 'Alert 5', translation: 'Тривога 5' },
  { term: 'Angled 1', translation: 'Кутовий 1' },
  { term: 'Angled 2', translation: 'Кутовий 2' },
  { term: 'Angled 3', translation: 'Кутовий 3' },
  { term: 'Angled 4', translation: 'Кутовий 4' },
  { term: 'Angled 5', translation: 'Кутовий 5' },
  { term: 'Arched', translation: 'Вигнутий' },
  { term: 'Arched Downward', translation: 'Вигнуті донизу' },
  { term: 'Arched Full', translation: 'Повна арка' },
  { term: 'Arched Intense', translation: 'Вигнутий інтенсивний' },
  { term: 'Arched Thin', translation: 'Худорлявий вигнутий' },
  { term: "Atom's Enlightenment", translation: 'Просвітлення Атома' },
  { term: "Atom's Sight", translation: 'Зір Атома' },
  { term: "Atom's Third Eye", translation: 'Третє око Атома' },
  { term: 'Atomic Cloud', translation: 'Атомна хмара' },
  { term: 'Average', translation: 'Середній' },
  { term: 'Average 1', translation: 'Середній 1' },
  { term: 'Average 2', translation: 'Середній 2' },
  { term: 'Average 3', translation: 'Середній 3' },
  { term: 'Average 4', translation: 'Середній 4' },
  { term: 'Average 5', translation: 'Середній 5' },
  { term: 'Average Arched', translation: 'Середньо — вигнутий' },
  { term: 'Average Dark', translation: 'Середньостатистичний темношкірий' },
  { term: 'Bad Luck Horseshoe', translation: 'Погане везіння' },
  { term: 'Bad Luck Horshoe', translation: 'Підкова невдачі' },
  { term: 'Blemishes', translation: 'Подразнення' },
  { term: 'Blush 1', translation: "Рум'янець 1" },
  { term: 'Blush 2', translation: "Рум'янець 2" },
  { term: 'Blush 3', translation: "Рум'янець 3" },
  { term: 'Boxer - 12 Rounds', translation: 'Боксер — 12 раундів' },
  { term: 'Boxer - Black Eye', translation: 'Боксер — чорне око' },
  { term: 'Boxer - Broken Nose', translation: 'Боксер — зламаний ніс' },
  { term: 'Boxer - Fat Lip', translation: 'Боксер — розбита губа' },
  { term: 'Brows', translation: 'Брови' },
  { term: 'Bushy', translation: 'Кущистий' },
  { term: 'Chain Reaction', translation: 'Ланцюгова реакція' },
  { term: 'Cheek Blemishes 1', translation: 'Висипи на щоках 1' },
  { term: 'Cheek Blemishes 2', translation: 'Висипи на щоках 2' },
  { term: 'Cheek Blemishes 3', translation: 'Висипи на щоках 3' },
  { term: 'Cheek Blemishes 4', translation: 'Висипи на щоках 4' },
  { term: 'Cheek Blemishes 5', translation: 'Висипи на щоках 5' },
  { term: 'Cheek Blemishes 6', translation: 'Висипи на щоках 6' },
  { term: 'Cheek Blemishes 7', translation: 'Висипи на щоках 7' },
  { term: 'Cheek Bones', translation: 'Вилиці' },
  { term: 'Cheek Bones Back', translation: 'Вилиці — задня частина' },
  { term: 'Cheek Creases', translation: 'Складки на щоках' },
  { term: 'Cheekbones', translation: 'Вилиці' },
  { term: 'Cheekbones - Back', translation: 'Вилиці — задня частина' },
  { term: 'Cheeks', translation: 'Щоки' },
  { term: 'Cheeks Gaunt', translation: 'Худкі щоки' },
  { term: 'Cheeks mask', translation: 'Маска щік' },
  { term: 'Chin', translation: 'Підборіддя' },
  { term: 'Chiseled 1', translation: 'Висічений 1' },
  { term: 'Chiseled 2', translation: 'Висічений 2' },
  { term: 'Chiseled 3', translation: 'Висічений 3' },
  { term: 'Chiseled 4', translation: 'Висічений 4' },
  { term: 'Chiseled 5', translation: 'Висічений 5' },
  { term: 'Chisleled 1', translation: 'Точений 1' },
  { term: 'Coal Miner', translation: 'Гірник' },
  { term: 'CraterFace1', translation: 'Кратерне обличчя' },
  { term: 'Creased', translation: 'Зморшкуватий' },
  { term: 'Curved', translation: 'Вигнутий' },
  { term: 'Damage', translation: 'Шкода' },
  { term: 'Dark Harlequin', translation: 'Темний Арлекін' },
  { term: 'Diamond Eyes', translation: 'Діамандові очі' },
  { term: 'Dirt', translation: 'Бруд' },
  { term: 'Dirt1', translation: 'Людина' },
  { term: 'Dirt3', translation: 'Дитина людини' },
  { term: 'Dirt4', translation: 'Бруд' },
  { term: 'Dirt5', translation: 'Дитина' },
  { term: 'Division', translation: 'Поділ' },
  { term: 'Double Radiance', translation: 'Подвійне сяйво' },
  { term: 'Downturned 1', translation: 'Знижений 1' },
  { term: 'Downturned 2', translation: 'Знижений 2' },
  { term: 'Downturned 3', translation: 'Знижений 3' },
  { term: 'Downturned 4', translation: 'Знижений 4' },
  { term: 'Downturned 5', translation: 'Знижений 5' },
  { term: 'Downward Straight', translation: 'Схилена вниз' },
  { term: 'Eagle', translation: 'Орел' },
  { term: 'Earlobes', translation: 'Мочки' },
  { term: 'Ears - Full', translation: 'Вуха — цілком' },
  { term: 'Ears - Middle', translation: 'Вуха — середня частина' },
  { term: 'Ears - Top', translation: 'Вуха — верхня частина' },
  { term: 'Ears And Chin', translation: 'Вуха та підборіддя' },
  { term: 'Ears Bottom', translation: 'Вуха — нижня частина' },
  { term: 'Ears Main', translation: 'Основна частина вуха' },
  { term: 'Ears mask', translation: 'Маска вух' },
  { term: 'Ears Mid', translation: 'Вуха — середня частина' },
  { term: 'Ears Top', translation: 'Вуха — верхня частина' },
  { term: 'Electron Eyes', translation: 'Електронні очі' },
  { term: 'Eye Black', translation: 'Підводка для очей' },
  { term: 'Eye Liner 1', translation: 'Підводка для очей' },
  { term: 'Eye Liner 2', translation: 'Підводка для очей 2' },
  { term: 'Eye Liner 3', translation: 'Підводка для очей 3' },
  { term: 'Eye Liner 4', translation: 'Підводка для очей 4' },
  { term: 'Eye Liner 5', translation: 'Підводка для очей 5' },
  { term: 'Eye Liner 6', translation: 'Підводка для очей 6' },
  { term: 'Eye Liner Lower 1', translation: 'Нижня лінія очей 1' },
  { term: 'Eye Liner Lower 2', translation: 'Нижня повіка 2' },
  { term: 'Eye Liner Waterline', translation: 'Підводка для слизової' },
  { term: 'Eye Shadow 1', translation: 'Тіні для повік 1' },
  { term: 'Eye Shadow 2', translation: 'Тіні для повік 2' },
  { term: 'Eye Shadow 3', translation: 'Тіні для повік 3' },
  { term: 'Eye Socket Shade', translation: 'Орбіта ока' },
  { term: 'Eyebrow In', translation: 'Брова — внутрішня частина' },
  { term: 'Eyebrow Main', translation: 'Брова — основна частина' },
  { term: 'Eyebrow Outer', translation: 'Брова — зовнішня частина' },
  { term: 'Eyebrows - Full', translation: 'Брови — цілком' },
  { term: 'Eyebrows - Inner', translation: 'Брови — внутрішня частина' },
  { term: 'Eyebrows - Middle', translation: 'Брови — середня частина' },
  { term: 'Eyebrows - Outer', translation: 'Брови — зовнішня частина' },
  { term: 'Eyebrows Mid', translation: 'Брови — середня частина' },
  { term: 'Eyelids - Bottom', translation: 'Нижня повіка' },
  { term: 'Eyelids - Top', translation: 'Верхня повіка' },
  { term: 'Eyes', translation: 'Очі' },
  { term: 'Eyes Gaunt', translation: 'Запалі очі' },
  { term: 'Eyes mask', translation: 'Маска для очей' },
  { term: 'Face - Lower', translation: 'Нижня частина обличчя' },
  { term: 'Face Paint', translation: 'Розпис обличчя' },
  { term: 'Face Smudge', translation: 'Бруд на обличчі' },
  { term: 'Face Tattoo 10', translation: 'Татуювання на обличчі 10' },
  { term: 'Face Tattoo 11', translation: 'Татуювання на обличчі 11' },
  { term: 'Face Tattoo 6', translation: 'Татуювання на обличчі 6' },
  { term: 'Face Tattoo 7', translation: 'Татуювання на обличчі 7' },
  { term: 'Face Tattoo 8', translation: 'Татуювання на обличчі 8' },
  { term: 'Face Tattoo 9', translation: 'Татуювання на обличчі 9' },
  { term: 'Face Tattoos', translation: 'Татуювання на обличчі' },
  { term: 'FaceDetails', translation: 'Деталі обличчя' },
  { term: 'FaceRegions', translation: 'Регіони обличчя' },
  { term: 'FemaleBrows1', translation: 'Жіночі брови 1' },
  { term: 'FemaleBrows2', translation: 'Жіночі брови 2' },
  { term: 'FemaleBrows3', translation: 'Жіночі брови 3' },
  { term: 'FemaleBrows4', translation: 'Жіночі брови 4' },
  { term: 'Firm 1', translation: 'Міцна 1' },
  { term: 'Firm 2', translation: 'Тверда 2' },
  { term: 'Firm 3', translation: 'Пружний 3' },
  { term: 'Firm 4', translation: 'Пружний 4' },
  { term: 'Firm 5', translation: 'Суворий 5' },
  { term: 'Forehead', translation: 'Лоб' },
  { term: 'Forehead Blemishes 1', translation: 'Висипи на лобі 1' },
  { term: 'Forehead Blemishes 2', translation: 'Висипи на лобі 2' },
  { term: 'Forehead Blemishes 3', translation: 'Висипи на лобі 3' },
  { term: 'Forehead Blemishes 4', translation: 'Висипи на лобі 4' },
  { term: 'Forehead Blemishes 5', translation: 'Висипи на лобі 5' },
  { term: 'Forehead Blemishes 6', translation: 'Висипи на лобі 6' },
  { term: 'Forehead Blemishes 7', translation: 'Висипи на лобі 7' },
  { term: 'Forehead mask', translation: 'Маска на чоло' },
  { term: 'Freckles - Lower', translation: 'Людина' },
  { term: 'Freckles - Middle', translation: 'Веснянки — середина' },
  { term: 'Freckles - Upper', translation: 'Веснянки — верхня' },
  { term: 'Freckles1', translation: 'Веснянки' },
  { term: 'Full', translation: 'Повна' },
  { term: 'Full 1', translation: 'Повний 1' },
  { term: 'Full 2', translation: 'Повний 2' },
  { term: 'Full 3', translation: 'Повний 3' },
  { term: 'Full 4', translation: 'Повний 4' },
  { term: 'Full 5', translation: 'Повний 5' },
  { term: 'Full Arch', translation: 'Людина' },
  { term: 'Full Diamond', translation: 'Повний діамант' },
  { term: 'Full Eye Black', translation: 'Повна чорна підводка' },
  { term: 'Full Eye Smudge', translation: 'Повне забруднення навколо очей' },
  { term: 'Full Eyeline', translation: 'Повна лінія очей' },
  { term: 'Full Pout 1', translation: 'Повна помада 1' },
  { term: 'Full Pout 2', translation: 'Повний вираз 2' },
  { term: 'Full Pout 3', translation: 'Повний вираз губ 3' },
  { term: 'Full Pout 4', translation: 'Людина' },
  { term: 'Full Pout 5', translation: 'Повний вираз губ 5' },
  { term: 'Full Pursed 1', translation: 'Повністю стиснуті губи 1' },
  { term: 'Full Pursed 2', translation: 'Повністю стиснуті губи 2' },
  { term: 'Full Pursed 3', translation: 'Людина' },
  { term: 'Full Pursed 4', translation: 'Повністю стиснуті губи 4' },
  { term: 'Full Pursed 5', translation: 'Людина' },
  { term: 'Fusion', translation: 'Злиття' },
  { term: 'Gridiron', translation: 'Людина' },
  { term: 'Grime', translation: 'Бруд' },
  { term: 'Grin 1', translation: 'Усмішка 1' },
  { term: 'Grin 2', translation: 'Усмішка 2' },
  { term: 'Grin 3', translation: 'Усмішка 3' },
  { term: 'Grin 4', translation: 'Усмішка 4' },
  { term: 'Grin 5', translation: 'Усмішка 5' },
  { term: 'Handsome 1', translation: 'Вродливий 1' },
  { term: 'Handsome 2', translation: 'Красунчик 2' },
  { term: 'Handsome 3', translation: 'Красунчик 3' },
  { term: 'Handsome 4', translation: 'Красунчик 4' },
  { term: 'Handsome 5', translation: 'Красунчик 5' },
  { term: 'Head Smudge', translation: 'Пляма на голові' },
  { term: 'Intense', translation: 'Інтенсивний' },
  { term: 'Jaw - Middle', translation: 'Середина щелепи' },
  { term: 'Jaw - Outer', translation: 'Щелепа — зовнішня частина' },
  { term: 'Jaw Mid', translation: 'Щелепа — середня частина' },
  { term: 'Jaw Outer', translation: 'Щелепа — зовнішня частина' },
  { term: 'Jowls -  Lower', translation: 'Нижні щоки' },
  { term: 'Jowls - Lower', translation: 'Нижні щоки' },
  { term: 'Jowls - Upper', translation: 'Верхні щоки' },
  { term: 'Large 1', translation: 'Великий 1' },
  { term: 'Large 2', translation: 'Великий 2' },
  { term: 'Large 3', translation: 'Великий 3' },
  { term: 'Large 4', translation: 'Великий 4' },
  { term: 'Large 5', translation: 'Великий 5' },
  { term: 'Light Tan', translation: 'Світло — бежевий' },
  { term: 'Lightning', translation: 'Блискавка' },
  { term: 'Lined', translation: 'Підкладка' },
  { term: 'Lip Color', translation: 'Колір губ' },
  { term: 'Lip Gloss', translation: 'Блиск для губ' },
  { term: 'Lip Liner', translation: 'Контур для губ' },
  { term: 'Lip Matte', translation: 'Матовий блиск' },
  { term: 'Lipstick', translation: 'Помада' },
  { term: 'Lobeless 1', translation: 'Без мочки 1' },
  { term: 'Lobeless 2', translation: 'Без мочки 2' },
  { term: 'Lobeless 3', translation: 'Без мочки 3' },
  { term: 'Lobeless 4', translation: 'Без мочки 4' },
  { term: 'Lobeless 5', translation: 'Без мочки 5' },
  { term: 'Long 1', translation: 'Довгий 1' },
  { term: 'Long 2', translation: 'Довгий 2' },
  { term: 'Long 3', translation: 'Довгий 3' },
  { term: 'Long 4', translation: 'Довгий 4' },
  { term: 'Long 5', translation: 'Довгий 5' },
  { term: 'Long Pout 1', translation: 'Довга пика 1' },
  { term: 'Long Pout 2', translation: 'Довга пика 2' },
  { term: 'Long Pout 3', translation: 'Довга пика 3' },
  { term: 'Long Pout 4', translation: 'Довга пика 4' },
  { term: 'Long Pout 5', translation: 'Довга пика 5' },
  { term: 'Low', translation: 'Низ' },
  { term: 'Lower Eye Shadow 1', translation: 'Нижня повіка 1' },
  { term: 'Lower Eye Shadow 2', translation: 'Нижня повіка 2' },
  { term: 'Lower Face', translation: 'Нижня частина обличчя' },
  { term: 'Lucky Clover', translation: 'Щаслива конюшня' },
  { term: 'Makeup', translation: 'Макіяж' },
  { term: 'MaleBrows1', translation: 'Чоловічі брови 1' },
  { term: 'MaleBrows2', translation: 'Чоловічі брови 2' },
  { term: 'MaleBrows3', translation: 'Чоловічі брови 3' },
  { term: 'MaleBrows4', translation: 'Чоловічі брови' },
  { term: 'Malformed 1', translation: 'Деформований 1' },
  { term: 'Malformed 2', translation: 'Деформований 2' },
  { term: 'Malformed 3', translation: 'Деформований 3' },
  { term: 'Malformed 4', translation: 'Деформований 4' },
  { term: 'Malformed 5', translation: 'Деформований 5' },
  { term: 'Markings', translation: 'Позначки' },
  { term: 'Mismatched 1', translation: 'Невідповідність 1' },
  { term: 'Mismatched 2', translation: 'Невідповідність 2' },
  { term: 'Mismatched 3', translation: 'Невідповідність 3' },
  { term: 'Mismatched 4', translation: 'Невідповідність 4' },
  { term: 'Mismatched 5', translation: 'Невідповідність 5' },
  { term: 'Moles - Cheek', translation: 'Родинки — щока' },
  { term: 'Moles - Full Face', translation: 'Родинки — все обличчя' },
  { term: 'Moles - Lower Face', translation: 'Людина' },
  { term: 'Moles - Nose', translation: 'Родинки — ніс' },
  { term: 'Mouth - Bottom', translation: 'Рот — нижня частина' },
  { term: 'Mouth - Corners', translation: 'Рот — кути' },
  { term: 'Mouth - Full', translation: 'Рот — цілком' },
  { term: 'Mouth - Top', translation: 'Рот — верхня частина' },
  { term: 'Mouth Blemishes 1', translation: 'Висипи на роті 1' },
  { term: 'Mouth Blemishes 2', translation: 'Висипи на роті 2' },
  { term: 'Mouth Blemishes 3', translation: 'Висипи на роті 3' },
  { term: 'Mouth Blemishes 4', translation: 'Висипи на роті 4' },
  { term: 'Mouth Blemishes 5', translation: 'Висипи на роті 5' },
  { term: 'Mouth Blemishes 6', translation: 'Висипи на роті 6' },
  { term: 'Mouth Blemishes 7', translation: 'Висипи на роті 7' },
  { term: 'Mouth Bot', translation: 'Рот — нижня частина' },
  { term: 'Mouth Corners', translation: 'Рот — кути' },
  { term: 'Mouth Grille', translation: 'Решітка рота' },
  { term: 'Mouth Main', translation: 'Рот — основна частина' },
  { term: 'Mouth mask', translation: 'Маска на рот' },
  { term: 'Mouth Smudge', translation: 'Пляма на роті' },
  { term: 'Mouth Stitch', translation: 'Шов на роті' },
  { term: 'Mouth Top', translation: 'Рот — верхня частина' },
  { term: 'Mud And Blood', translation: 'Бруд і кров' },
  { term: 'Muscular', translation: "М'язистий" },
  { term: 'Narrow 1', translation: 'Вузький 1' },
  { term: 'Narrow 2', translation: 'Вузький 2' },
  { term: 'Narrow 3', translation: 'Вузький 3' },
  { term: 'Narrow 4', translation: 'Вузький 4' },
  { term: 'Narrow 5', translation: 'Вузький 5' },
  { term: 'Nautical Anchor', translation: 'Морський якір' },
  { term: 'Neck', translation: 'Шия' },
  { term: 'Neck Fat', translation: 'Шия, товста' },
  { term: 'Neck mask', translation: 'Маска на шию' },
  { term: 'No One', translation: 'Ніхто' },
  { term: 'Nose - Bridge', translation: 'Переносиця' },
  { term: 'Nose - Full', translation: 'Ніс — цілком' },
  { term: 'Nose - Ridge', translation: 'Гребінь носа' },
  { term: 'Nose - Tip', translation: 'Кінчик носа' },
  { term: 'Nose Bridge', translation: 'Переносиця' },
  { term: 'Nose Main', translation: 'Ніс — основна частина' },
  { term: 'Nose mask', translation: 'Маска на ніс' },
  { term: 'Nose Tip', translation: 'Кінчик носа' },
  { term: 'Nostrils', translation: 'Ніздрі' },
  { term: 'Nuclear Devotee', translation: 'Ядерний фанатик' },
  { term: 'Oily', translation: 'Маслянистий' },
  { term: 'Overgrown', translation: 'Зарослий' },
  { term: 'Piercing 1', translation: 'Пронизливий 1' },
  { term: 'Piercing 2', translation: 'Пронизливий 2' },
  { term: 'Piercing 3', translation: 'Пронизливий 3' },
  { term: 'Piercing 4', translation: 'Пронизливий 4' },
  { term: 'Piercing 5', translation: 'Пронизливий 5' },
  { term: 'Pocked Face', translation: 'Покрите виразками обличчя' },
  { term: 'Pocked Neck', translation: 'Покрита виразками шия' },
  { term: 'Pocks1', translation: 'Людина' },
  { term: 'Pout 1', translation: 'Надутий 1' },
  { term: 'Pout 2', translation: 'Надутий 2' },
  { term: 'Pout 3', translation: 'Надутий 3' },
  { term: 'Pout 4', translation: 'Надутий 4' },
  { term: 'Pout 5', translation: 'Надутий 5' },
  { term: 'Pretty 1', translation: 'Красуня 1' },
  { term: 'Pretty 2', translation: 'Приваблива 2' },
  { term: 'Pretty 3', translation: 'Приваблива 3' },
  { term: 'Pretty 4', translation: 'Симпатична 4' },
  { term: 'Pretty 5', translation: 'Приваблива 5' },
  { term: 'Prominent 1', translation: 'Виразний 1' },
  { term: 'Prominent 2', translation: 'Виразний 2' },
  { term: 'Prominent 3', translation: 'Виразний 3' },
  { term: 'Prominent 4', translation: 'Виразний 4' },
  { term: 'Prominent 5', translation: 'Виразний 5' },
  { term: 'Pug 1', translation: 'Мопс 1' },
  { term: 'Pug 2', translation: 'Мопс 2' },
  { term: 'Pug 3', translation: 'Мопс 3' },
  { term: 'Pug 4', translation: 'Мопс 4' },
  { term: 'Pug 5', translation: 'Мопс 5' },
  { term: 'Pursed 1', translation: 'Людина' },
  { term: 'Pursed 2', translation: 'Піджатий 2' },
  { term: 'Pursed 3', translation: 'Піджатий 3' },
  { term: 'Pursed 4', translation: 'Людина' },
  { term: 'Pursed 5', translation: 'Піджатий 5' },
  { term: 'Rad Harzard', translation: 'Рад Харзард' },
  { term: 'Rad Hazard', translation: 'Радіаційна загроза' },
  { term: 'Radiance', translation: 'Сяйво' },
  { term: 'Radiation Dust', translation: 'Радіаційний пил' },
  { term: 'Radiation Skull', translation: 'Радіаційний череп' },
  { term: 'Rashed', translation: 'Рашед' },
  { term: 'Red Nose', translation: 'Червоний ніс' },
  { term: 'Rested 1', translation: 'Відпочивший 1' },
  { term: 'Rested 2', translation: 'Відпочивший 2' },
  { term: 'Rested 3', translation: 'Відпочивший 3' },
  { term: 'Rested 4', translation: 'Відпочивший 4' },
  { term: 'Rested 5', translation: 'Відпочивший 5' },
  { term: 'Ridged', translation: 'З ребром' },
  { term: 'Roman 1', translation: 'Римський 1' },
  { term: 'Roman 2', translation: 'Римський 2' },
  { term: 'Roman 3', translation: 'Римський 3' },
  { term: 'Roman 4', translation: 'Римський 4' },
  { term: 'Roman 5', translation: 'Римський 5' },
  { term: 'Rough Face', translation: 'Необроблена поверхня обличчя' },
  { term: 'Rounded 1', translation: 'Закруглена 1' },
  { term: 'Rounded 2', translation: 'Закруглена 2' },
  { term: 'Rounded 3', translation: 'Округле 3' },
  { term: 'Rounded 4', translation: 'Закруглена 4' },
  { term: 'Rounded 5', translation: 'Закруглена 5' },
  { term: 'Ruddy', translation: "Рум'яний" },
  { term: 'Scar - Center Burn', translation: 'Шрам — центр опіку' },
  { term: 'Scar - Cheek Burn', translation: 'Шрам — опік на щоці' },
  { term: 'Scar - Chin', translation: 'Шрам — підборіддя' },
  { term: 'Scar - Forced Smile', translation: 'Шрам — примусова посмішка' },
  { term: 'Scar - Forehead', translation: 'Шрам — чоло' },
  { term: 'Scar - Head Burn', translation: 'Шрам — опік на голові' },
  { term: 'Scar - Left Back Deep', translation: 'Шрам — ліва частина спини, глибокий' },
  { term: 'Scar - Left Brow Gash', translation: 'Шрам — ліва брова' },
  { term: 'Scar - Left Brow Small', translation: 'Шрам — ліва брова (малий)' },
  { term: 'Scar - Left Long', translation: 'Шрам — лівий довгий' },
  { term: 'Scar - Lip Cut', translation: 'Шрам на губі' },
  { term: 'Scar - Lip Gouges', translation: 'Шрами на губах' },
  { term: 'Scar - Lip Scratch', translation: 'Шрам на губі' },
  { term: 'Scar - Middle Deep', translation: 'Шрам — середина' },
  { term: 'Scar - Nose Arch', translation: 'Переносиця' },
  { term: 'Scar - Nose Gouge', translation: 'Шрам — вирваний ніс' },
  { term: 'Scar - Right Brow Deep', translation: 'Шрам — права брова (глибокий)' },
  { term: 'Scar - Right Brow Long', translation: 'Шрам — права брова, довгий' },
  { term: 'Scar - Right Burn', translation: 'Шрам — правий опік' },
  { term: 'Scar - Right Gouge', translation: 'Шрам — права борозда' },
  { term: 'Scar - Right Stitches', translation: 'Шрам — права строчка' },
  { term: 'Scar1', translation: 'Гуль' },
  { term: 'Scar2', translation: 'Гуль' },
  { term: 'Scar3', translation: 'Гуль' },
  { term: 'Scar4', translation: 'Гуль' },
  { term: 'Scar5', translation: 'Гуль' },
  { term: 'Scars', translation: 'Шрами' },
  { term: 'Serious', translation: 'Серйозний' },
  { term: 'Shifty 1', translation: 'Швидкий 1' },
  { term: 'Shifty 2', translation: 'Неспокійний 2' },
  { term: 'Shifty 3', translation: 'Хитрий 3' },
  { term: 'Shifty 4', translation: 'Шифті 4' },
  { term: 'Shifty 5', translation: 'Мінливий 5' },
  { term: 'Shrewd 1', translation: 'Хитрий 1' },
  { term: 'Shrewd 2', translation: 'Хитрий 2' },
  { term: 'Shrewd 3', translation: 'Хитрий 3' },
  { term: 'Shrewd 4', translation: 'Хитрий 4' },
  { term: 'Shrewd 5', translation: 'Хитрий 5' },
  { term: 'Side Nose Fat', translation: 'Крило носа, пухке' },
  { term: 'Skin tone', translation: 'Колір шкіри' },
  { term: 'SkinTints', translation: 'Відтінки шкіри' },
  { term: 'Slight Rash', translation: 'Легкий висип' },
  { term: 'Small 1', translation: 'Малий 1' },
  { term: 'Small 2', translation: 'Малий 2' },
  { term: 'Small 3', translation: 'Малий 3' },
  { term: 'Small 4', translation: 'Малий 4' },
  { term: 'Small 5', translation: 'Малий 5' },
  { term: 'Smirk 1', translation: 'Посмішка' },
  { term: 'Smirk 2', translation: 'Посмішка 2' },
  { term: 'Smirk 3', translation: 'Посмішка 3' },
  { term: 'Smirk 4', translation: 'Посмішка 4' },
  { term: 'Smirk 5', translation: 'Посмішка 5' },
  { term: 'Smooth', translation: 'Гладка' },
  { term: 'Solid', translation: 'Міцний' },
  { term: 'Splattered', translation: 'Заляпаний' },
  { term: 'Splotches - Chin', translation: 'Плями — підборіддя' },
  { term: 'Splotches - Left Cheek', translation: 'Плями — ліва щока' },
  { term: 'Splotches - Left Eye', translation: 'Плями — ліве око' },
  { term: 'Splotches - Left Head', translation: 'Плями — ліва частина голови' },
  { term: 'Splotches - Neck', translation: 'Плями — шия' },
  { term: 'Splotches - Right Cheek', translation: 'Плями — права щока' },
  { term: 'Splotches - Right Head', translation: 'Плями — права частина голови' },
  { term: 'Splotchy1', translation: 'Гуль' },
  { term: 'Splotchy2', translation: 'Гуль' },
  { term: 'Splotchy3', translation: 'Гуль' },
  { term: 'Splotchy4', translation: 'Плямиста' },
  { term: 'Splotchy5', translation: 'Людина' },
  { term: 'Spots1', translation: 'Гуль' },
  { term: 'Spots2', translation: 'Гуль' },
  { term: 'Strained 1', translation: 'Напружений 1' },
  { term: 'Strained 2', translation: 'Напружений 2' },
  { term: 'Strained 3', translation: 'Напружений 3' },
  { term: 'Strained 4', translation: 'Напружений 4' },
  { term: 'Strained 5', translation: 'Напружений 5' },
  { term: 'Sun Scorched', translation: 'Сонцепек' },
  { term: 'Suspicious 1', translation: 'Підозрілий 1' },
  { term: 'Suspicious 2', translation: 'Підозрілий 2' },
  { term: 'Suspicious 3', translation: 'Підозрілий 3' },
  { term: 'Suspicious 4', translation: 'Підозрілий 4' },
  { term: 'Suspicious 5', translation: 'Підозрілий 5' },
  { term: 'Temple', translation: 'Скроня' },
  { term: 'Temples', translation: 'Скроні' },
  { term: 'Textured', translation: 'Текстурований' },
  { term: 'Thick 1', translation: 'Товста 1' },
  { term: 'Thick 2', translation: 'Товстий 2' },
  { term: 'Thick 3', translation: 'Товстий 3' },
  { term: 'Thick 4', translation: 'Товста 4' },
  { term: 'Thick 5', translation: 'Товщина 5' },
  { term: 'Thick Arch', translation: 'Товста арка' },
  { term: 'Thick Downward', translation: 'Людина' },
  { term: 'Thick Light', translation: 'Товсте світло' },
  { term: 'Thick Raised', translation: 'Товсті підняті' },
  { term: 'Thick Scarred', translation: 'Товстошкірий' },
  { term: 'Thick Short', translation: 'Товстий, низький' },
  { term: 'Thick Straight', translation: 'Густе пряме' },
  { term: 'Thin', translation: 'Тонке' },
  { term: 'Thin 1', translation: 'Тонка 1' },
  { term: 'Thin 2', translation: 'Тонка 2' },
  { term: 'Thin 3', translation: 'Тонка 3' },
  { term: 'Thin 4', translation: 'Тонка 4' },
  { term: 'Thin 5', translation: 'Тонка 5' },
  { term: 'Thin Arched', translation: 'Тонка вигнута' },
  { term: 'Thin Rounded', translation: 'Тонке закруглене' },
  { term: 'Throat Smudge', translation: 'Заплямована гортань' },
  { term: 'Throat Stitch', translation: 'Шов на горлі' },
  { term: 'Tired 1', translation: 'Втомлений 1' },
  { term: 'Tired 2', translation: 'Втомлений 2' },
  { term: 'Tired 3', translation: 'Втомлений 3' },
  { term: 'Tired 4', translation: 'Втомлений 4' },
  { term: 'Tired 5', translation: 'Втомлений 5' },
  { term: 'Trench Warfare', translation: 'Окопна війна' },
  { term: 'Tribal', translation: 'Племінник' },
  { term: 'Untamed', translation: 'Неприборканий' },
  { term: 'Warband', translation: 'Варбанд' },
  { term: 'Weathered', translation: 'Вивітрений' },
  { term: 'Wide 1', translation: 'Широкий 1' },
  { term: 'Wide 2', translation: 'Широкий 2' },
  { term: 'Wide 3', translation: 'Широкий 3' },
  { term: 'Wide 4', translation: 'Широкий 4' },
  { term: 'Wide 5', translation: 'Широкий 5' },
  { term: 'Worried 1', translation: 'Стривожений 1' },
  { term: 'Worried 2', translation: 'Стривожений 2' },
  { term: 'Worried 3', translation: 'Стривога 3' },
  { term: 'Worried 4', translation: 'Стривожений 4' },
  { term: 'Worried 5', translation: 'Стривога 5' },
  { term: 'Wrinkled', translation: 'Зморшкуватий' },
];
