import type { GlossaryEntry } from './types';

/** Canonical Oblivion EN→UK terminology for prompts. */
export const OB_UK_GLOSSARY: GlossaryEntry[] = [
  { term: 'Imperial City', translation: 'Імперське місто' },
  { term: 'Blades', translation: 'Клинки' },
  { term: 'Mythic Dawn', translation: 'Міфічний світанок' },
  { term: 'Dark Brotherhood', translation: 'Темне братство' },
  { term: 'Mages Guild', translation: 'Гільдія магів' },
  { term: 'Fighters Guild', translation: 'Гільдія воїнів' },
  { term: 'Thieves Guild', translation: 'Гільдія злодіїв' },
  { term: 'Knights of the Nine', translation: "Лицарі Дев'ятки" },
  { term: 'Oblivion', translation: 'Забуття' },
  { term: 'Shivering Isles', translation: 'Тремтячі острови' },
  { term: 'Dremora', translation: 'дрімора' },
  { term: 'Clannfear', translation: 'кланфір' },
  { term: 'Minotaur', translation: 'мінотавр' },
  { term: 'Ogre', translation: 'огр' },
  { term: 'Anvil', translation: 'Ейнвіл' },
  { term: 'Bravil', translation: 'Бравіл' },
  { term: 'Bruma', translation: 'Брума' },
  { term: 'Cheydinhal', translation: 'Чейдінхол' },
  { term: 'Kvatch', translation: 'Кватч' },
  { term: 'Leyawiin', translation: 'Леявін' },
  { term: 'Skingrad', translation: 'Скінград' },
  { term: 'Chorrol', translation: 'Чоррол' },
  { term: 'Mysticism', translation: 'містицизм' },
  { term: 'Alteration', translation: 'трансмутація' },
  { term: 'Blade', translation: 'клинок' },
  { term: 'Blunt', translation: 'дроблячка' },
];
